### ISSUE TITLE
Add load/example helper

### ISSUE THREAD

**Issue by dgleich** [nassarhuda/MatrixNetworks.jl#1]
It'd be nice to have a helper function to load data:

```
A = load_matrix_network_graph("clique-10")
(A,meta) = load_matrix_network_data("clique-10") # load additional metadata
matrix_network_datasets() # Provide a list of datasets
```

The implementation of load_matrix_network_graph would just be really simple:

```
function load_matrix_network_graph(name::AbstractString)

   basename = joinpath(dirname(@__FILE__), "..", "data", name)

    smatname = joinpath(basename, string(dataset_name, ".smat"))
    if isfile(rdaname)
        return readSMAT(read_rda(rdaname)[dataset_name])
    else
        error(@sprintf "The example datafile '%s' does not seem to exist where it should\n" name)
    end

end
```

See https://github.com/johnmyleswhite/RDatasets.jl for more examples

**Comment by nassarhuda** [comment]
load_matrix_network: (slightly different that what you suggested)
https://github.com/nassarhuda/MatrixNetworks.jl/blob/master/src/load_matrix_network.jl

matrix_network_datasets:
https://github.com/nassarhuda/MatrixNetworks.jl/blob/master/src/matrix_network_datasets.jl

Sample in readme.md:
https://github.com/nassarhuda/MatrixNetworks.jl#data-available

**Comment by dgleich** [comment]
Awesome. But load_matrix_network should probably have a fixed return type. The problem is that the return type varies based on whether or not there is metadata there. So it'd be really annoying to use this function in a loop:

for graph in matrix_networks_datasets():
  A = load_matrix_network(graph)

**Comment by nassarhuda** [comment]
I can return (readSMAT(smatfile),[],[]) for the datasets with no metadata. Do you think that would a good solution to the problem?

On another note, the above for loop won't work because:
matrix_networks_datatsets() returns the name with '.smat' extension; load_matrix_network works on the name of the dataset without the extension. I think I have to be consistent there too. Will make matrix_networks_datatsets() return the datasets' names without '.smat'

**Comment by nassarhuda** [comment]
All functions related to managing data are now here:
https://github.com/nassarhuda/MatrixNetworks.jl/blob/master/src/manage_data.jl

Data folder no longer has a metadata subfolder. Metadata files are now identified by their extension (.xy or .labels)

**Comment by nassarhuda** [comment]
This has been taken care of too, I think I can close it now.
