### ISSUE TITLE
PageRank code

### ISSUE THREAD

**Issue by dgleich** [nassarhuda/MatrixNetworks.jl#10]
It'd be good to have a robust, efficient PageRank code in Julia. This issue is just to have an initial implementation we can start from.

**Comment by sbromberger** [comment]
ref:

https://gist.github.com/domluna/2b9358ccc89fee7d5e26
https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/centrality/pagerank.jl
https://github.com/purzelrakete/Pagerank.jl

**Comment by dgleich** [comment]
Thanks! We have a draft implementation too in one of my repos, but these are useful to see the other interfaces that folks have adopted.
