### ISSUE TITLE
load_matrix_network_metadata

### ISSUE THREAD

**Issue by dgleich** [nassarhuda/MatrixNetworks.jl#12]
It'd be nice if the metadata reader could return xy coords without needed labels, e.g. 

```
matrix_network_datasets()
(A,xy) = load_matrix_network_metadata("cores_example")
```

**Comment by nassarhuda** [comment]
That will bring us to 3 functions for reading data

```
load_matrix_network
load_matrix_network_metadata # (A, xy) without labels
load_matrix_network_alldata # returns everything - or maybe a struct
```

Note that 

```
(A,xy,~) = load_matrix_network_metadata("airports")
```

would still give A and xy ignoring labels

**Comment by dgleich** [comment]
The issue I'm running into is that there are networks with coordinates
without labels, and vice-versa...

Maybe we should just have metadata return a dictionary with all the types
of possible metadata?

David

**Comment by nassarhuda** [comment]
What do you think of this:

```
types = matrix_network_types("airports")
(A,xy,labels) = load_matrix_network_data("airports","network","coords","labels")

# this should also work:
(A,labels) = load_matrix_network_data("airports","network","labels")
# or
(A,xy) = load_matrix_network_data("airports","network","coords")
```

i.e. first argument is dataset name and the remaining strings are the types requested (which can be obtained from `matrix_network_types`)
If an unavailable type is requested an error is produced.

My point is to keep this at 2 functions, keeping things as standard as possible

**Comment by dgleich** [comment]
Oh, maybe the solution is just to return an empty array if the field doesn't exist, rather than creating more work :)

We only have two types of metadata, 

labels and xy 

right?

David
