### ISSUE TITLE
Fix Lint errors

### ISSUE THREAD

**Issue by dgleich** [nassarhuda/MatrixNetworks.jl#2]
We should try and fix all the Lint errors

```
using Lint
lintpkg("MatrixNetworks")
```

And then add this as a test once it passes cleanly.

**Comment by dgleich** [comment]
The current lint errors are:

```
/home/dgleich/.julia/v0.4/MatrixNetworks/src/readSMAT.jl
/home/dgleich/.julia/v0.4/MatrixNetworks/src/floydwarshall.jl
/home/dgleich/.julia/v0.4/MatrixNetworks/src/MatrixNetworks.jl:41 [               ] ERROR  duplicate exports of symbol strong_components_map
/home/dgleich/.julia/v0.4/MatrixNetworks/src/bfs.jl:19 [bfs            ] INFO   Argument declared but not used: v
/home/dgleich/.julia/v0.4/MatrixNetworks/src/bipartite_matching.jl:27 [               ] INFO   Julia style recommends type names start with an upper case: matching_setup
/home/dgleich/.julia/v0.4/MatrixNetworks/src/bipartite_matching.jl:39 [               ] INFO   Julia style recommends type names start with an upper case: matching_output
/home/dgleich/.julia/v0.4/MatrixNetworks/src/bipartite_matching.jl:168 [bipartite_matching_primal_dual] INFO   Argument declared but not used: tripi
/home/dgleich/.julia/v0.4/MatrixNetworks/src/readSMAT.jl:3 [readSMAT       ] ERROR  Use of undeclared symbol :
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:33 [               ] INFO   Julia style recommends type names start with an upper case: strong_components_output
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:37 [               ] INFO   A type is not given to the field map, which can be slow.
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:38 [               ] INFO   A type is not given to the field sizes, which can be slow.
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:39 [               ] INFO   A type is not given to the field number, which can be slow.
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:40 [               ] INFO   A type is not given to the field A, which can be slow.
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:43 [               ] INFO   Julia style recommends type names start with an upper case: strong_components_rich_output
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:44 [               ] INFO   A type is not given to the field reduction_matrix, which can be slow.
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:45 [               ] INFO   A type is not given to the field transitive_order, which can be slow.
/home/dgleich/.julia/v0.4/MatrixNetworks/src/scomponents.jl:46 [               ] INFO   A type is not given to the field transitive_map, which can be slow.
```

**Comment by nassarhuda** [comment]
All resolved now except for 1 error, we can talk about it tomorrow

**Comment by nassarhuda** [comment]
Here is the current output of 

```
intpkg("MatrixNetworks")
```

```
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/MatrixNetwork.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/scomponents.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/csr_to_sparse.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/sparse_to_csr.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bipartite_matching.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/dfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/clustercoeffs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/corenums.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/floydwarshall.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/largest_component.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bfs.jl:19 [bfs            ] INFO   Argument declared but not used: v
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl:44 [matrix_network_datasets] ERROR  Use of undeclared symbol end
```

**Comment by dgleich** [comment]
It looks like there is a bug in bfs.m with regards to the use of “v”, can you confirm?

Can you also use the lint hint thingy to ignore that error on end?

Thanks,
David

On July 3, 2015 at 2:23:36 PM, Huda Nassar (notifications@github.com) wrote:

Here is the current output of

intpkg("MatrixNetworks")

/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/MatrixNetwork.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/scomponents.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/csr_to_sparse.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/sparse_to_csr.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bipartite_matching.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/dfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/clustercoeffs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/corenums.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/floydwarshall.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/largest_component.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bfs.jl:19 [bfs            ] INFO   Argument declared but not used: v
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl:44 [matrix_network_datasets] ERROR  Use of undeclared symbol end

**Comment by nassarhuda** [comment]
bfs uses v in the code but it's within an if statement and this is why Lint sees it as declared but not used

The above comment is wrong - I got confused with another problem I have previously run into. It's not Lint's problem anyway. Now this is fixed. The only remaining error is not accepting the 'end', I'll look into ignoring certain lines and once it passes cleanly I'll add it as a test.

**Comment by nassarhuda** [comment]
Here is the current output:

```
julia> lintpkg("MatrixNetworks")
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/MatrixNetwork.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/scomponents.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/csr_to_sparse.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/sparse_to_csr.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bipartite_matching.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/dfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/clustercoeffs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/corenums.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/floydwarshall.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/largest_component.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl:44 [matrix_network_datasets] ERROR  Use of undeclared symbol end
```

**Comment by dgleich** [comment]
Okay, almost done — but can you add a lintpragma statement to skip the error on “end”?

Thanks,
David

On July 3, 2015 at 6:18:34 PM, Huda Nassar (notifications@github.com) wrote:

Here is the current output:

julia> lintpkg("MatrixNetworks")
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/MatrixNetwork.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/scomponents.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/csr_to_sparse.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/sparse_to_csr.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bipartite_matching.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/dfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/clustercoeffs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/corenums.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/floydwarshall.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/largest_component.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl:44 [matrix_network_datasets] ERROR  Use of undeclared symbol end

**Comment by nassarhuda** [comment]
Done.

```
julia> msgs = lintpkg( "MatrixNetworks", returnMsgs = true )
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/MatrixNetwork.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/scomponents.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/csr_to_sparse.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/sparse_to_csr.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bipartite_matching.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/bfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/dfs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/clustercoeffs.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/corenums.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/floydwarshall.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/manage_data.jl
/Users/hudanassar/.julia/v0.4/MatrixNetworks/src/largest_component.jl
0-element Array{Lint.LintMessage,1}

julia> @assert(isempty(msgs))

```

I have two more functions that I'm planning to upload today, will make sure they're lint clean and then add lint as a test.

**Comment by dgleich** [comment]
Awesome. Let's close this after you add the check

**Comment by nassarhuda** [comment]
Lint is now part of runtests.jl. I will close this now.
