### ISSUE TITLE
Compat range of Arpack not set to latest version

### ISSUE THREAD

**Issue by ghost** [nassarhuda/MatrixNetworks.jl#66]
Currently the `Project.toml` constrains `Arpack` to be 0.4.0, whereas [the latest version](https://github.com/JuliaLinearAlgebra/Arpack.jl) is 0.5.3. This is causing clashes with other packages.

**Comment by dgleich** [comment]
So just bump this to Arpack = "0.4, 0.5" ?

**Comment by agrimsm** [comment]
I made a PR to bump this in #67. The tests seem to pass, so hopefully this is fine?

**Comment by agrimsm** [comment]
Any chance we could get a minor release with this change?

**Comment by dgleich** [comment]
@nassarhuda can you set a new release? (Also, the code now uses genericarpack instead of arpack.)
