### ISSUE TITLE
Add @dgleich as a collaborator?

### ISSUE THREAD

**Issue by dgleich** [nassarhuda/MatrixNetworks.jl#74]
Hey @ViralShah, do you know how @nassarhuda and/or someone else can add @dgleich as a collaborator to this repo so I can get write access? @nassarhuda tried and she doesn't have a "settings" option on the page when she looks at Github, so there didn't seem to be a way to add me.

**Comment by dgleich** [comment]
oops, wrong @ViralBShah

**Comment by ViralBShah** [comment]
Invited to the org.
