### ISSUE TITLE
Spectral cuts

### ISSUE THREAD

**Issue by dgleich** [nassarhuda/MatrixNetworks.jl#9]
We need a spectral cut function to compute a spectral bipartition based on the normalized Laplacian matrix.

**Comment by jpfairbanks** [comment]
Just a heads up, I wrote a simple package to help me study the differences between using different graph matrices for spectral partitioning. https://github.com/jpfairbanks/GraphMatrices.jl/. It lets you take an arbitrary graph/matrix type and get the adjacency/laplacian along with right/left/symmetric normalization without extra storage. You can then use the resulting type as an input to `eigs`, or an iterative linear solver.

**Comment by dgleich** [comment]
Neat! That could be useful.

**Comment by nassarhuda** [comment]
#15 closes this
